services:
  - type: web
    name: marketpro
    env: docker
    region: oregon
    plan: free
    healthCheckPath: /
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        sync: false
      - key: ConnectionStrings__Redis
        sync: false
    dockerfilePath: ./Dockerfile 