services:
  - type: web
    name: marketpro
    env: dotnet
    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet ./out/MarketPro.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        sync: false
      - key: ConnectionStrings__Redis
        sync: false 